version: "2"

run:
  timeout: 5m
  tests: true

linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - revive
    - gocritic

linters-settings:
  errcheck:
    exclude-functions:
      - (net/http.ResponseWriter).Write
      - (*encoding/json.Encoder).Encode
      - (*http.Response).Body.Close
      - (*os.File).Close
      - fmt.Fprint
      - fmt.Fprintf

  revive:
    severity: warning
    rules:
      - name: var-naming
      - name: early-return

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
