name: Go Lint (reviewdog)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  checks: write
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  golangci:
    name: runner / golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v7

      - name: Set up Go
        uses: actions/setup-go@v7
        with:
          go-version: 'stable'
          cache: false

      - name: Run golangci-lint with reviewdog (PR)
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
          level: warning
          fail_level: none
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m ./..."

      - name: Run golangci-lint with reviewdog (push)
        if: github.event_name == 'push'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          filter_mode: nofilter
          level: warning
          fail_level: warning
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m ./..."
