name: Go Lint (reviewdog)

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  checks: write   # nötig für github-pr-check

jobs:
  golangci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-go@v6
        with:
          go-version-file: go.mod
          cache: true

      - name: Run golangci-lint with reviewdog (PR)
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          filter_mode: added
          level: warning
          fail_level: none
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m ./..."

      - name: Run golangci-lint with reviewdog (push)
        if: github.event_name == 'push'
        uses: reviewdog/action-golangci-lint@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-check
          filter_mode: nofilter
          level: warning
          fail_level: warning
          golangci_lint_flags: "--config=.golangci.yml --timeout=5m ./..."
